spring.application.name=rssdemo
spring.datasource.url=jdbc:postgresql://ider-database.westeurope.cloudapp.azure.com:5432/h602111
spring.datasource.username=h602111
spring.datasource.password=1998821Kk

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=rssdemo
spring.jpa.show-sql=true
